<?php

declare(strict_types=1);

namespace Webconsulting\RecordsListTypes\Html;

use Override;
use TYPO3\CMS\Core\Html\DefaultSanitizerBuilder;
use TYPO3\HtmlSanitizer\Behavior;
use TYPO3\HtmlSanitizer\Behavior\Attr;
use TYPO3\HtmlSanitizer\Behavior\Tag;

/**
 * Sanitizer preset for TYPO3 backend component/button fragments.
 *
 * The custom views render HTML generated by TYPO3 backend APIs
 * (DatabaseRecordList, ComponentFactory, icons, web components). This builder
 * extends TYPO3's default sanitizer with the backend-specific tags and
 * attributes required for those fragments.
 */
final class BackendFragmentSanitizerBuilder extends DefaultSanitizerBuilder
{
    #[Override]
    protected function createBehavior(): Behavior
    {
        $behavior = parent::createBehavior();

        $commonBackendAttrs = [
            ...$this->globalAttrs,
            new Attr('popover'),
            new Attr('popovertarget'),
            new Attr('disabled'),
            new Attr('hidden'),
        ];

        $buttonAttrs = [
            ...$commonBackendAttrs,
            new Attr('type'),
            new Attr('name'),
            new Attr('value'),
        ];

        $anchorAttrs = [
            ...$commonBackendAttrs,
            $this->hrefAttr,
            ...$this->createAttrs('download', 'hreflang', 'ping', 'rel', 'referrerpolicy', 'target', 'type'),
        ];

        $inputAttrs = array_merge(
            $commonBackendAttrs,
            [
                new Attr('type'),
                new Attr('name'),
                new Attr('value'),
                new Attr('checked'),
            ],
        );
        $contextualTriggerAttrs = array_merge(
            $commonBackendAttrs,
            [
                new Attr('url'),
                new Attr('edit-url'),
            ],
        );
        $downloadButtonAttrs = array_merge(
            $commonBackendAttrs,
            [
                new Attr('url'),
                new Attr('subject'),
                new Attr('ok'),
                new Attr('close'),
            ],
        );
        $newPageWizardAttrs = array_merge(
            $commonBackendAttrs,
            [
                new Attr('configuration'),
            ],
        );
        $columnSelectorAttrs = array_merge(
            $commonBackendAttrs,
            [
                new Attr('url'),
                new Attr('table'),
                new Attr('identifier'),
                new Attr('preset'),
                new Attr('return-url'),
            ],
        );
        $clipboardPanelAttrs = array_merge(
            $commonBackendAttrs,
            [
                new Attr('return-url'),
            ],
        );

        // TYPO3's DefaultSanitizerBuilder pipes every <svg> through SvgSanitizer
        // with removeRemoteReferences(true). That strips
        // <use xlink:href="/_assets_install/.../sprites/actions.svg#id"/> out of
        // every backend icon and leaves an empty <svg>, which is then purged --
        // so all icons in buttons produced by IconFactory disappear.
        //
        // The fragments we sanitize here are generated by TYPO3 Core
        // (IconFactory, DatabaseRecordList) and reference TYPO3's own sprite
        // assets, so the SVG markup is trusted. Replace the inherited svg
        // handler with a plain Tag entry and explicitly allow the SVG child
        // elements that Core emits. `withNodes` keys by node name, so a new
        // `Tag('svg')` overrides the inherited NodeHandler.
        $svgAttrs = [
            ...$this->globalAttrs,
            ...$this->createAttrs('viewbox', 'width', 'height', 'fill', 'stroke', 'xmlns', 'xmlns:xlink', 'preserveaspectratio'),
        ];
        $useAttrs = [
            ...$this->globalAttrs,
            ...$this->createAttrs('x', 'y', 'width', 'height', 'href', 'xlink:href'),
        ];
        $pathAttrs = [
            ...$this->globalAttrs,
            ...$this->createAttrs('d', 'fill', 'stroke', 'stroke-width', 'fill-rule', 'clip-rule'),
        ];
        $shapeAttrs = [
            ...$this->globalAttrs,
            ...$this->createAttrs('cx', 'cy', 'r', 'rx', 'ry', 'x', 'y', 'x1', 'y1', 'x2', 'y2', 'width', 'height', 'points', 'd', 'fill', 'stroke', 'stroke-width', 'transform'),
        ];

        return $behavior->withTags(
            (new Tag('svg', Tag::ALLOW_CHILDREN))->addAttrs(...$svgAttrs),
            (new Tag('use'))->addAttrs(...$useAttrs),
            (new Tag('path'))->addAttrs(...$pathAttrs),
            (new Tag('g', Tag::ALLOW_CHILDREN))->addAttrs(...$shapeAttrs),
            (new Tag('defs', Tag::ALLOW_CHILDREN))->addAttrs(...$this->globalAttrs),
            (new Tag('symbol', Tag::ALLOW_CHILDREN))->addAttrs(...$svgAttrs),
            (new Tag('title', Tag::ALLOW_CHILDREN))->addAttrs(...$this->globalAttrs),
            (new Tag('circle'))->addAttrs(...$shapeAttrs),
            (new Tag('rect'))->addAttrs(...$shapeAttrs),
            (new Tag('line'))->addAttrs(...$shapeAttrs),
            (new Tag('polygon'))->addAttrs(...$shapeAttrs),
            (new Tag('polyline'))->addAttrs(...$shapeAttrs),
            (new Tag('ellipse'))->addAttrs(...$shapeAttrs),
            (new Tag('button', Tag::ALLOW_CHILDREN))->addAttrs(...$buttonAttrs),
            (new Tag('input'))->addAttrs(...$inputAttrs),
            (new Tag('a', Tag::ALLOW_CHILDREN))->addAttrs(...$anchorAttrs),
            (new Tag('typo3-backend-contextual-record-edit-trigger', Tag::ALLOW_CHILDREN))->addAttrs(...$contextualTriggerAttrs),
            (new Tag('typo3-recordlist-record-download-button'))->addAttrs(...$downloadButtonAttrs),
            (new Tag('typo3-backend-new-page-wizard-button'))->addAttrs(...$newPageWizardAttrs),
            (new Tag('typo3-backend-column-selector-button'))->addAttrs(...$columnSelectorAttrs),
            (new Tag('typo3-backend-clipboard-panel'))->addAttrs(...$clipboardPanelAttrs),
        );
    }
}
