<?php

declare(strict_types=1);

namespace Webconsulting\RecordsListTypes\Html;

use TYPO3\CMS\Core\Html\DefaultSanitizerBuilder;
use TYPO3\HtmlSanitizer\Behavior;
use TYPO3\HtmlSanitizer\Behavior\Attr;
use TYPO3\HtmlSanitizer\Behavior\Tag;

/**
 * Sanitizer preset for TYPO3 backend component/button fragments.
 *
 * The custom views render HTML generated by TYPO3 backend APIs
 * (DatabaseRecordList, ComponentFactory, icons, web components). This builder
 * extends TYPO3's default sanitizer with the backend-specific tags and
 * attributes required for those fragments.
 */
final class BackendFragmentSanitizerBuilder extends DefaultSanitizerBuilder
{
    protected function createBehavior(): Behavior
    {
        $behavior = parent::createBehavior();

        $commonBackendAttrs = [
            ...$this->globalAttrs,
            new Attr('popover'),
            new Attr('popovertarget'),
            new Attr('inert'),
            new Attr('disabled'),
            new Attr('hidden'),
        ];

        $buttonAttrs = [
            ...$commonBackendAttrs,
            new Attr('type'),
            new Attr('name'),
            new Attr('value'),
            new Attr('form'),
            new Attr('formaction'),
            new Attr('formenctype'),
            new Attr('formmethod'),
            new Attr('formnovalidate'),
            new Attr('formtarget'),
        ];

        $anchorAttrs = [
            ...$commonBackendAttrs,
            $this->hrefAttr,
            ...$this->createAttrs('download', 'hreflang', 'ping', 'rel', 'referrerpolicy', 'target', 'type'),
        ];

        return $behavior->withTags(
            (new Tag('button', Tag::ALLOW_CHILDREN))->addAttrs(...$buttonAttrs),
            (new Tag('input'))->addAttrs(
                ...$commonBackendAttrs,
                new Attr('type'),
                new Attr('name'),
                new Attr('value'),
                new Attr('checked'),
                new Attr('placeholder'),
                new Attr('min'),
                new Attr('max'),
                new Attr('step'),
                new Attr('autocomplete'),
            ),
            (new Tag('select', Tag::ALLOW_CHILDREN))->addAttrs(
                ...$commonBackendAttrs,
                new Attr('name'),
                new Attr('multiple'),
                new Attr('size'),
            ),
            (new Tag('option', Tag::ALLOW_CHILDREN))->addAttrs(
                new Attr('value'),
                new Attr('selected'),
                new Attr('disabled'),
                ...$commonBackendAttrs,
            ),
            (new Tag('optgroup', Tag::ALLOW_CHILDREN))->addAttrs(
                new Attr('label'),
                new Attr('disabled'),
                ...$commonBackendAttrs,
            ),
            (new Tag('form', Tag::ALLOW_CHILDREN))->addAttrs(
                ...$commonBackendAttrs,
                new Attr('action'),
                new Attr('method'),
                new Attr('novalidate'),
            ),
            (new Tag('a', Tag::ALLOW_CHILDREN))->addAttrs(...$anchorAttrs),
            (new Tag('typo3-backend-contextual-record-edit-trigger', Tag::ALLOW_CHILDREN))->addAttrs(
                ...$commonBackendAttrs,
                new Attr('url'),
                new Attr('edit-url'),
            ),
            (new Tag('typo3-recordlist-record-download-button'))->addAttrs(
                ...$commonBackendAttrs,
                new Attr('url'),
                new Attr('subject'),
                new Attr('ok'),
                new Attr('close'),
            ),
            (new Tag('typo3-backend-new-page-wizard-button'))->addAttrs(
                ...$commonBackendAttrs,
                new Attr('configuration'),
            ),
            (new Tag('typo3-backend-column-selector-button'))->addAttrs(
                ...$commonBackendAttrs,
                new Attr('url'),
                new Attr('table'),
                new Attr('identifier'),
                new Attr('preset'),
                new Attr('return-url'),
            ),
            (new Tag('typo3-backend-clipboard-panel'))->addAttrs(
                ...$commonBackendAttrs,
                new Attr('return-url'),
            ),
        );
    }
}
