<?php

declare(strict_types=1);

namespace Webconsulting\RecordsListTypes\Html;

use TYPO3\CMS\Core\Html\DefaultSanitizerBuilder;
use TYPO3\HtmlSanitizer\Behavior;
use TYPO3\HtmlSanitizer\Behavior\Attr;
use TYPO3\HtmlSanitizer\Behavior\Tag;

/**
 * Sanitizer preset for TYPO3 backend component/button fragments.
 *
 * The custom views render HTML generated by TYPO3 backend APIs
 * (DatabaseRecordList, ComponentFactory, icons, web components). This builder
 * extends TYPO3's default sanitizer with the backend-specific tags and
 * attributes required for those fragments.
 */
final class BackendFragmentSanitizerBuilder extends DefaultSanitizerBuilder
{
    protected function createBehavior(): Behavior
    {
        $behavior = parent::createBehavior();

        $globalAttrs = [
            ...$this->globalAttrs,
            new Attr('aria-', Attr::NAME_PREFIX),
            new Attr('data-', Attr::NAME_PREFIX),
            new Attr('popovertarget'),
            new Attr('popover'),
            new Attr('type'),
            new Attr('name'),
            new Attr('value'),
            new Attr('disabled'),
            new Attr('checked'),
            new Attr('selected'),
            new Attr('hidden'),
            new Attr('configuration'),
            new Attr('subject'),
            new Attr('ok'),
            new Attr('close'),
            new Attr('url'),
            new Attr('return-url'),
            new Attr('edit-url'),
        ];

        return $behavior->withTags(
            (new Tag('typo3-backend-contextual-record-edit-trigger', Tag::ALLOW_CHILDREN))->addAttrs(...$globalAttrs),
            (new Tag('typo3-recordlist-record-download-button'))->addAttrs(...$globalAttrs),
            (new Tag('typo3-backend-new-page-wizard-button'))->addAttrs(...$globalAttrs),
            (new Tag('typo3-backend-clipboard-panel'))->addAttrs(...$globalAttrs),
        );
    }
}
